### ISSUE TITLE
just asking

### ISSUE THREAD

**Issue by crossomen** [Krasnikov05/socks5mitm#2]
do you have any plan to add tls-interception on this proxy?
This one is the most stable simple socks5proxy.
unlike other, it never crash when i test and no requirement for other unnecessary python package.
it would be perfect mitm-socks5proxy with just one more tls-interception on.

**Comment by Krasnikov05** [comment]
Of course, I will add this, but a little later. I need time to figure out how to get this to work stably on Windows.
